"""rooms delete is_booked

Revision ID: cb9e6736ca3d
Revises: bf803255ce5f
Create Date: 2023-12-09 21:08:25.803346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb9e6736ca3d'
down_revision: Union[str, None] = 'bf803255ce5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'is_booked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('is_booked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
